### ISSUE TITLE
How are we doing Create [Member/Rental/Branch]?

### ISSUE THREAD

**Issue by MattRyder** [InvertedLlama/PPSD#5]
Just wondering if anyone had a roadmap for what we're doing in terms of user interaction?

I would've gone with a Form, they enter the new record, use an INSERT INTO statement to send it to the DB.

If that's agreed, I'll get onto mocking up some forms for these, just wanted to check beforehand if there were any better ideas.

**Comment by cfehunter** [comment]
You've got two ways of doing it. That way with a seperate form or you can let the user type the data into the controls on the main form and then add a new row to the data table when they click apply.

Either way will work fine but the seperate form will probably be easier to implement.

**Comment by cfehunter** [comment]
You edited that :p

Anyway what I ended up doing was this.

Form for each add button, internally referd to and treated as a dialogue.

Each form has an event called RecordAdded which is only called if the data is sucessfully inserted into the database via an INSERT INTO X (y, z) style query.

Rentals are more complicated because I had to account for available stock. So with rentals there are two forms and the procedure is like this.

1.) Add Items to the order (via second form)
2.) Insert rental record into the rental table
3.) insert items into the rentalItem table
4.) Update available stock values
5.) Notify listeners of the RecordAdded event
